# Generated by Django 4.2.7 on 2024-01-21 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_lesson_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonpage',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_pages', to='base.lesson'),
        ),
    ]
