# Generated by Django 4.2.7 on 2024-01-21 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_lessonpage_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='lessonpage',
            new_name='lesson_page',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_completed',
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'lesson_page')},
        ),
    ]
